- web/app/paymaster-bundler/_components/Header.tsx
- web/app/paymaster-bundler/_components/Vault.tsx
> fix: build bugs

- contracts/script/D01DeployTracker.s.sol
update script to include strava challenge
> chore: update script to include strava challenge

- contracts/script/D01DeployTracker.s.sol
- contracts/src/Tracker.sol
- contracts/test/Tracker.t.sol
- web/app/api/sign/route.ts
- web/app/habit/checkin/components/checkin.tsx
- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/checkin/components/nfc.tsx
- web/app/habit/checkin/components/stamps.tsx
- web/app/habit/claim/components/claim.tsx
- web/app/habit/components/UserDashboard.tsx
- web/app/habit/stake/components/dropdown.tsx
- web/app/habit/stake/page.tsx
- web/src/constants.ts
- web/src/contracts/tracker.ts
- web/src/hooks/useUserChallenges.ts
- web/src/hooks/useUserCheckIns.ts
Update address to use new `Tracker` at `0x2B1d06d53C8597d586690A49776E5B3b4bf2eC61`
* type hash cannot contain space between fields.
> feat: update FE to use new contract (checkIn by ID)

- web/app/api/sign/route.ts
- web/app/habit/checkin/components/checkin.tsx
- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/checkin/components/nfc.tsx
- web/app/habit/claim/components/claim.tsx
- web/app/habit/components/UserDashboard.tsx
- web/app/habit/components/step4.tsx
- web/app/habit/components/step4failed.tsx
- web/app/habit/page.tsx
- web/app/habit/stake/components/dropdown.tsx
- web/app/habit/stake/page.tsx
- web/package.json
- web/src/constants.ts
- web/src/contracts/tracker.ts
- web/src/hooks/useAllChallenges.ts
- web/src/hooks/useUserChallenges.ts
- web/src/hooks/useUserCheckIns.ts
- web/src/store/createWagmiConfig.ts
- web/src/types.ts
- web/src/utils/timestamp.ts
- web/yarn.lock
Todo
Most data are available from the contract, only a few need to be specified: (as metadata)
* type
* name
* mapKey (if needed as NFC challenge)
use `useAllChallenges` to fetch all challenge details, replace hardcoded `challenges`.
> feat: remove hardcode challenge data

- web/app/habit/components/UserDashboard.tsx
- web/src/hooks/useAllChallenges.ts
* Show "join other challenges" last on the dashboard page
* Sort by start date
> ui: dashboard order change

- web/app/connect-run/page.tsx
- web/app/habit/checkin/components/CheckinPopup.tsx
- web/app/habit/checkin/components/activityDropdown.tsx
- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/claim/components/ClaimedPopup.tsx
- web/app/habit/claim/components/claim.tsx
- web/app/habit/components/Onboard.tsx
- web/app/habit/create/components/step1.tsx
- web/app/habit/create/components/step2.tsx
- web/app/habit/create/components/step3.tsx
- web/app/habit/stake/components/DepositPopup.tsx
- web/app/habit/stake/components/InsufficientBalancePopup.tsx
- web/app/habit/stake/components/JoinedPopup.tsx
- web/app/habit/stake/components/stakeContent.tsx
- web/src/components/PopupWindow/PopupWindow.css
- web/src/components/PopupWindow/PopupWindow.tsx
- web/src/hooks/transaction/useCheckInRun.ts
* Unified button by using `Button` from nextui, color="primary", invariant="bordered". 
* Removed additional loading content logic for buttons, just use `isLoading`
* Simplified the activity dropdown by nextui Select component
> ui: button and dropdown

- web/app/habit/checkin/components/activityDropdown.tsx
- web/app/habit/checkin/components/checkinRun.tsx
- web/src/hooks/transaction/useCheckInRun.ts
- web/src/hooks/useFields.ts
* useFields.ts: Adding the new `useFields` hook to manage all the states that you need when submitting txs.
* Move all the tx arguments back to component and computed when activity is selected.
> refactor: tx hook

- web/app/habit/components/NavbarFooter.tsx
- web/app/habit/create/components/createContent.tsx
- web/app/habit/create/components/step1.tsx
Original implementation was wrong and somehow doesn't update the "startTimestamp" correctly.
Updated the logic to the same as nextui example
> fix: weird date picker bug

- contracts/src/Tracker.sol
- contracts/src/interfaces/ICheckInJudge.sol
* Add view functions for challenge participant counts
* settlement can be blocked if donation address is 0
* can settle non-existing challenges
* natspec
* public to external
> feat: natspec, random bugs and view function

- contracts/script/D01DeployTracker.s.sol
- contracts/src/Tracker.sol
- web/app/api/sign/route.ts
- web/app/habit/checkin/components/CheckinPopup.tsx
- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/checkin/components/nfc.tsx
- web/app/habit/components/ChallengeBox.tsx
- web/app/habit/components/NavbarFooter.tsx
- web/app/habit/create/components/createContent.tsx
- web/src/contracts/tracker.ts
- web/src/hooks/transaction/useCheckInRun.ts
- web/src/hooks/transaction/useCreate.ts
- web/src/hooks/useAllChallenges.ts
- web/src/hooks/useChallenge.ts
- web/src/types.ts
* Update to use new contract (customized underlying, new signing scheme)
* Fix contract EIP712 bug (didn't hash the bytes)
* Fetch participant counts!
> feat: new contracts

- web/app/api/strava/[activityType]/route.ts
- web/app/api/strava/utils/index.ts
- web/app/habit/checkin/components/activityDropdown.tsx
- web/app/habit/checkin/components/checkin.tsx
- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/components/Onboard.tsx
- web/app/habit/create/components/step3.tsx
- web/src/constants.ts
- web/src/hooks/useActivityUsage.ts
- web/src/hooks/useRunData.ts
- web/src/utils/challenges.ts
- web/src/utils/strava.ts
* Add cycling on Strava
* Show loading ring when "connecting" so it looks less buggy
* `usedActivities` were not updated when wallet changes (or re-connect)
* Old: When use chose an activity first, then hit connect (it's more often that we loss connection with session key connector), the checkin button is still disabled because `sign` api can only be triggered when activity is "selected"
* fix: update to use `useEffect` to fetch signature, updated whenever address or `chosenActivityId` changes, we refetch the signature
* safe guard: don't allow choosing activity when `address` is undefined
> feat: Add cycling

- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/components/ChallengeBox.tsx
- web/app/habit/components/InviteLink.tsx
- web/app/habit/components/UserDashboard.tsx
- web/app/habit/create/components/step3.tsx
- web/app/habit/stake/components/stakeContent.tsx
- web/app/layout.tsx
- web/app/page.tsx
- web/src/hooks/useChallengeMetaData.ts
* Fix challenge box not aligned
* Fix challenge list margin too big
* Add an invite link to check in page
> fix: some style fixes + share button on checkin page

- web/.eslintrc.js
- web/app/Providers.tsx
- web/app/connect-run/page.tsx
- web/app/connect-run/strava/page.tsx
- web/app/habit/checkin/components/activityDropdown.tsx
- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/checkin/components/nfc.tsx
- web/app/habit/claim/components/claim.tsx
- web/app/habit/components/ChallengeBox.tsx
- web/app/habit/components/InviteLink.tsx
- web/app/habit/components/NavbarFooter.tsx
- web/app/habit/components/UserDashboard.tsx
- web/app/habit/create/components/step2.tsx
- web/app/habit/create/components/step3.tsx
- web/app/habit/stake/components/stakeContent.tsx
- web/app/install/components/InstallButton.tsx
- web/app/layout.tsx
- web/app/page.tsx
- web/app/profile/components/ProfileContent.tsx
- web/app/profile/page.tsx
- web/next.config.js
- web/package.json
- web/src/hooks/useChallengeMetaData.ts
- web/src/hooks/useSocialShare.ts
- web/src/hooks/useUserChallenges.ts
- web/src/types.ts
- web/src/utils/address.ts
- web/yarn.lock
* Fix install page broken because of CSR and layout issue
* remove unnecessary nextPWA usage
* Add simple profile page
* 謝謝狸貓
> fix: fix install page and everything PWA

- web/app/habit/stake/components/DepositPopup.tsx
- web/app/habit/stake/components/stakeContent.tsx
- web/src/components/Connect/ConnectButton.tsx
- web/src/hooks/transaction/useCheckInRun.ts
- web/src/hooks/transaction/useJoinChallenge.ts
- web/src/hooks/transaction/useTransferERC20.ts
- web/src/hooks/transaction/useWithdraw.ts
- web/src/hooks/usePasskeyConnection.ts
Add tracker for the following events:
* click on register / login (successfully)
* join, checkin, claim
* open deposit modal + withdraw money out (transfer out)
> feat: add event trackers

- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/components/ChallengeBox.tsx
- web/app/habit/components/UserDashboard.tsx
- web/src/constants.ts
- web/src/utils/challenges.ts
- web/src/utils/timestamp.ts
> feat: CircularProgress indicator

- web/app/habit/components/NavbarFooter.tsx
- web/app/habit/create/components/createContent.tsx
- web/app/layout.tsx
- web/app/profile/components/ProfileContent.tsx
> fix: annoying navbar footer

- web/app/habit/checkin/components/activityDropdown.tsx
- web/app/habit/checkin/components/checkinRun.tsx
- web/app/habit/claim/components/claim.tsx
- web/app/habit/components/InviteLink.tsx
- web/app/habit/components/NavbarFooter.tsx
- web/app/habit/components/UserDashboard.tsx
- web/app/habit/create/components/createContent.tsx
- web/app/habit/create/components/step1.tsx
- web/app/habit/history/components/HistoryContent.tsx
- web/app/habit/list/components/challengeList.tsx
- web/app/habit/stake/components/DepositPopup.tsx
- web/app/habit/stake/components/stakeContent.tsx
- web/app/profile/components/ProfileContent.tsx
- web/src/hooks/transaction/useCheckInRun.ts
- web/src/hooks/transaction/useJoinChallenge.ts
- web/src/hooks/transaction/useTransferERC20.ts
- web/src/hooks/usePasskeyConnection.ts
- web/src/hooks/useSocialShare.ts
- web/src/utils/gtag.ts
> feat: trackers

- web/app/api/frame/[[...routes]]/route.tsx
- web/app/api/frame/utils/constants.ts
- web/app/habit/checkin/components/CheckinPopup.tsx
- web/app/withdraw/components/SpecialWithdraw.tsx
- web/src/hooks/transaction/useTransactionArbitraryChain.ts
- web/src/hooks/useSocialShare.ts
Use query string to encode and decode query correctly.
> fix: frame url encode use query string

- web/app/api/create/route.ts
- web/app/habit/checkin/components/ActivityCheckIn.tsx
- web/app/habit/claim/components/claim.tsx
- web/app/habit/create/components/createContent.tsx
- web/app/habit/create/components/step1.tsx
- web/app/habit/stake/components/stakeContent.tsx
- web/src/hooks/useStravaData.ts
- web/src/types.ts
- web/src/utils/challenges.ts
In this pull request, we add the feature to add additional requirement(time, distance) in a challenge.
- Add new input (minDistance, minTime) while creating challenge
- Filter unqualified activities
- Fix challenge status error in claim
> feat: additional filter activities

- web/src/types.ts
couldn't claim because enum type is wrong, always setting needSettle = true
> fix: cannot claim

- web/app/habit/checkin/components/ActivityCheckIn.tsx
- web/app/habit/claim/components/ClaimedPopup.tsx
- web/app/habit/claim/components/claim.tsx
- web/app/habit/components/UserDashboard.tsx
- web/app/home/HomePage.tsx
- web/src/components/Connect/RegisterButton.tsx
1. Update claimed modal to show amounts claimed (resolves #214) (screenshot 1)
2. Fix not showing history when no ongoing challenge (resolves #213) (screenshot 2)
3. Fix negative countdown in checkin page
> feat: feedback + fixes

- web/app/habit/checkin/components/ActivityCheckIn.tsx
- web/app/habit/checkin/components/ManualCheckInButton.tsx
- web/app/habit/checkin/components/activityDropdown.tsx
fix #198 
- 改用 localString() format distance data
- 增加 checkin dropdown and button width 已顯示更多資訊
> Fix checkin bugs

- web/app/habit/checkin/components/ManualCheckInButton.tsx
- web/app/habit/checkin/components/activityDropdown.tsx
- web/app/habit/claim/components/claim.tsx
- web/app/habit/components/UserDashboard.tsx
- web/app/habit/history/components/HistoryContent.tsx
- web/app/habit/utils/sortChallenges.ts
- web/src/utils/timestamp.ts
> feat: sort challenge

- web/app/Providers.tsx
- web/app/api/frame/[[...routes]]/route.tsx
- web/app/api/user/farcaster/route.ts
- web/app/profile/components/ProfileContent.tsx
- web/app/profile/components/QRCodeDialog.tsx
- web/app/profile/components/SignInButton.tsx
- web/app/profile/components/utils/mobile.ts
- web/package.json
- web/src/constants.ts
- web/src/providers/UserProfileProvider.tsx
- web/yarn.lock
In this pull request we implement the feature to allow user to connect and disconnect Warpcast to the account in the profile page.
closed #83 
Achieved through 
- web/app/profile/components/QRCodeDialog.tsx
- web/app/profile/components/SignInButton.tsx
And added a new provider to load profile related information
Please test in web and mobile browser
- Should be able Connect to Farcaster
- Should be able to load Farcaster profile after reload
- Should be able to Disconnect to Farcaster
> feat: connect farcaster
